#!/bin/sh
set -e

tmp="$(mktemp -d)"
remove_tmp () {
  rm -rf "$tmp"
}
trap remove_tmp EXIT

git ls-files -z "*.js" "*.css" "*.html" | xargs -0 -I{} cp {} "$tmp"
printf "@charset 'utf-8';\n\n" > "$tmp/readable.css"
cat normalize.css readable.css code.css >> "$tmp/readable.css"

tree "$tmp"
site=css.kemitchell.com
rsync --archive --delete --no-perms "$tmp/" "$site:/var/www/$site"
